import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const pg = await b.newPage({ viewport: { width: 390, height: 844 } });
pg.on('console', m => console.log('console', m.text()));
pg.on('pageerror', e => console.log('pageerror', e.message));
await pg.route(/googletagmanager|trustindex|youtube|google\.com\/maps/, (r) => r.abort());
await pg.goto('http://localhost:4321/consulta-online/', { waitUntil: 'load' });
const n = await pg.evaluate(() => { const f = document.querySelector('form.belba-form'); return [...f.querySelectorAll('[data-step]')].map(s => ({ hidden: s.hidden, txt: s.innerText.slice(0, 60), inputs: [...s.querySelectorAll('input')].map(i => i.type + ':' + i.name + (i.required ? '*' : '')) })); });
console.log(JSON.stringify(n, null, 1));
await b.close();
